<?php

namespace AppBundle\Repository;

/**
 * TGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
