# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: ROLE_ADMIN
         ROLE_BNI:         [ROLE_USER]
         ROLE_ADMIN:       [ROLE_BNI]
         ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        in_memory:
#            memory: ~
        fos_userbundle:
#            id: fos_user.user_provider.username
             id: fos_user.user_provider.username_email


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
                #always_use_default_target_path: true
                default_target_path: admin_payments_index
                always_use_default_target_path: true

            logout:       true
            anonymous:    true
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
    
    access_control:
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }
         - { path: ^/[a-z]+/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/[a-z]+/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/[a-z]+/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin/, role: ROLE_BNI }
#        - { path: '^/[a-z]+/[a-z]+_admin/', role: IS_AUTHENTICATED_FULLY }
#        - { path: '^/[a-z]+/[a-z]+_[a-z]+_admin/', role: IS_AUTHENTICATED_FULLY }
#        - { path: '^/[a-z]+/[a-z]+_[a-z]+_[a-z]+_admin/', role: IS_AUTHENTICATED_FULLY }
         - { path: '^/[a-z]+/admin_+[a-z]/', role: ROLE_ADMIN }
         - { path: '^/[a-z]+/admin_+[a-z]+_[a-z]/', role: ROLE_ADMIN }
         - { path: '^/[a-z]+/admin_+[a-z]+_[a-z]+_[a-z]/', role: ROLE_ADMIN }
