admin_binbank_index:
    path:     /
    defaults: { _controller: "AppBundle:BinBank:index" }
    methods:  GET

admin_binbank_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:BinBank:show" }
    methods:  GET

admin_binbank_new:
    path:     /new
    defaults: { _controller: "AppBundle:BinBank:new" }
    methods:  [GET, POST]

admin_binbank_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:BinBank:edit" }
    methods:  [GET, POST]

admin_binbank_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:BinBank:delete" }
    methods:  DELETE
