admin_bincode_index:
    path:     /
    defaults: { _controller: "AppBundle:BinCode:index" }
    methods:  GET

admin_bincode_update_bin_details:
    path:     /importBinDetails
    defaults: { _controller: "AppBundle:BinCode:importBinDetails" }
    methods:  GET
    
admin_bincode_import_bin_list:
    path:     /importBinList
    defaults: { _controller: "AppBundle:BinCode:importBinList" }
    methods:  GET


#admin_bincode_show:
#    path:     /{id}/show
#    defaults: { _controller: "AppBundle:BinCode:show" }
#    methods:  GET
#
#admin_bincode_new:
#    path:     /new
#    defaults: { _controller: "AppBundle:BinCode:new" }
#    methods:  [GET, POST]

admin_bincode_edit:
    path:     /{bin}/edit
    defaults: { _controller: "AppBundle:BinCode:edit" }
    methods:  [GET, POST]

#admin_bincode_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "AppBundle:BinCode:delete" }
#    methods:  DELETE
