admin_tgroup_index:
    path:     /
    defaults: { _controller: "AppBundle:Tgroup:index" }
    methods:  GET

admin_tgroup_show:
    path:     /{fgroupid}/show
    defaults: { _controller: "AppBundle:Tgroup:show" }
    methods:  GET

admin_tgroup_new:
    path:     /new
    defaults: { _controller: "AppBundle:Tgroup:new" }
    methods:  [GET, POST]

admin_tgroup_edit:
    path:     /{fgroupid}/edit
    defaults: { _controller: "AppBundle:Tgroup:edit" }
    methods:  [GET, POST]
   
admin_tgroup_delete:
    path:     /{fgroupid}/delete
    defaults: { _controller: "AppBundle:Tgroup:delete" }
    methods:  DELETE
