admin_payments_index:
    path:     /
    defaults: { _controller: "AppBundle:Tpayments:index" }
    methods:  GET
    
admin_payments_next_payments:
    path:     /next-payments
    defaults: { _controller: "AppBundle:Tpayments:nextPayments" }
    methods:  [GET, POST]


admin_payments_payment_forecasts:
    path:     /payment-forecasts
    defaults: { _controller: "AppBundle:Tpayments:paymentForecasts" }
    methods:  [GET, POST]


admin_payments_simulator:
    path:     /simulator
    defaults: { _controller: "AppBundle:Tpayments:simulator" }
    methods:  [GET, POST]


admin_payments_show:
    path:     /{fpurchaseid}/show
    defaults: { _controller: "AppBundle:Tpayments:show" }
    methods:  GET

admin_payments_new:
    path:     /new
    defaults: { _controller: "AppBundle:Tpayments:new" }
    methods:  [GET, POST]

admin_payments_edit:
    path:     /{fpurchaseid}/edit
    defaults: { _controller: "AppBundle:Tpayments:edit" }
    methods:  [GET, POST]

admin_payments_delete:
    path:     /{fpurchaseid}/delete
    defaults: { _controller: "AppBundle:Tpayments:delete" }
    methods:  DELETE

admin_payments_blank:
    path:     /blank
    defaults: { _controller: "AppBundle:Tpayments:blank" }
    methods:  [GET, POST]